/*
 * Provider bindings are generated by running `cdktf get`.
 * See https://cdk.tf/provider-generation for more details.
 */
import { DnsRecord } from "./.gen/providers/cloudflare/dns-record";
import { CloudflareProvider } from "./.gen/providers/cloudflare/provider";
import { Zone } from "./.gen/providers/cloudflare/zone";

import { Construct } from "constructs";
import { App, TerraformStack, CloudBackend, NamedCloudWorkspace, VariableType, TerraformVariable } from "cdktf";

export class MyStack extends TerraformStack {
  constructor(scope: Construct, id: string) {
    super(scope, id);

    /*Terraform Variables are not always the best fit for getting inputs in the context of Terraform CDK.
You can read more about this at https://cdk.tf/variables*/
    const cloudflareApiToken = new TerraformVariable(
      this,
      "cloudflare_api_token",
      {
        type: VariableType.STRING,
      }
    );

    function createZone(scope: Construct, name: string, zoneName: string) {
      return new Zone(scope, name, {
        account: { id: "2764ae0fd9a5cb92c9ac67708620e54c" },
        name: zoneName,
      });
    }

    function createDnsRecord(
      scope: Construct,
      name: string,
      zone: Zone,
      recordName: string,
      content: string,
      proxied: boolean
    ) {
      return new DnsRecord(scope, name, {
        content,
        name: recordName,
        proxied,
        ttl: 1,
        type: "A",
        zoneId: zone.id,
      });
    }

    function createCnameRecord(
      scope: Construct,
      name: string,
      zone: Zone,
      recordName: string,
      content: string
    ) {
      return new DnsRecord(scope, name, {
        content,
        name: recordName,
        proxied: false,
        ttl: 1,
        type: "CNAME",
        zoneId: zone.id,
      });
    }

    createZone(this, "autolife-ai", "autolife.ai");
    const autolifeTech = createZone(this, "autolife-tech", "auto-life.tech");
    createZone(this, "autolife.dpdns.org", "autolife.dpdns.org");
    createZone(this, "xiongchenyu.dpdns.org", "xiongchenyu.dpdns.org");
    createZone(this, "sexy.qzz.io", "sexy.qzz.io");

    new CloudflareProvider(this, "cloudflare", {
      apiToken: cloudflareApiToken.stringValue,
    });

    createDnsRecord(this, "frp_dashboard_autolife", autolifeTech, "frp-dashboard", "138.2.95.174", false);
    createDnsRecord(this, "mainpage_autolife", autolifeTech, "autolife-robotics.me", "138.2.95.174", true);
    createDnsRecord(this, "mngt_autolife", autolifeTech, "mngt", "138.2.95.174", false);
    createDnsRecord(this, "netbird_autolife", autolifeTech, "netbird", "138.2.95.174", false);
    createDnsRecord(this, "rust-server_autolife", autolifeTech, "rust-server", "138.2.95.174", false);
    createDnsRecord(this, "vr_sg_autolife", autolifeTech, "vr-sg", "138.2.95.174", false);
    createDnsRecord(this, "www_autolife", autolifeTech, "www", "138.2.95.174", true);
    createDnsRecord(this, "ollama", autolifeTech, "ollama", "138.2.95.174", false);
    createDnsRecord(this, "api", autolifeTech, "api", "138.2.95.174", false);
    createCnameRecord(this, "freeman_cname", autolifeTech, "freeman", "cname.vercel-dns.com.");
    createDnsRecord(this, "kanidm", autolifeTech, "kanidm", "213.35.97.233", false);

  }
}

const app = new App({
  skipValidation: true
});

const stack = new MyStack(app, "cdktf");

new CloudBackend(stack, {
  hostname: "app.terraform.io",
  organization: "autolife-robotics",
  workspaces: new NamedCloudWorkspace("cdktf"),
});

app.synth();
